import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* Left */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>
        {/* Right */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>
          {/* Icon */}
          {/* Avatar */}
          <Avatar url='https://media.comicbook.com/2018/09/goku-dragon-ball-super-1135574-1280x0.jpeg'/>
        </div>
      </header>
      {/* Body */}

      {/* Footer */}
    </div>
  )
}
